import {describe,expect,it,vi} from "vitest";
import {createAgentApi,MemoryRunStore,type AgentRuntime,type AgentApiAdapters} from "../src/gateway/api/index.js";
const auth=async(token:string)=>token==="Bearer good"?{subject:"u1",tenantId:"t1",scopes:["agent:write","agent:read","approval:decide","agent:cancel"]}:token==="Bearer other"?{subject:"u2",tenantId:"t1",scopes:["agent:write","agent:read","approval:decide","agent:cancel"]}:token==="Bearer admin"?{subject:"admin",tenantId:"t1",scopes:["agent:admin"]}:null;
const runtime:AgentRuntime={start:vi.fn(async(i,ctx)=>{ctx.emit("started",{sessionId:i.sessionId});ctx.emit("completed",{answer:"ok",rawTransaction:"secret"});}),cancel:vi.fn(async()=>true),health:async()=>({status:"ok",model:"ready"})};
const adapters:AgentApiAdapters={sessions:{get:async(id,t)=>id==="s1"&&t==="t1"?{id,title:"One"}:undefined,search:async()=>[{id:"s1"}]},approvals:{get:async(id)=>({id,status:"pending"}),decide:async(id,d)=>({id,status:d})}};
const req=(method:string,url:string,extra:any={})=>({method,url,...extra,headers:{authorization:"Bearer good",...extra.headers}});
describe("authenticated agent control API",()=>{
 it("authenticates, isolates tenancy, enforces quota, body limits and structured errors",async()=>{const api=createAgentApi({authenticate:auth,runtime,store:new MemoryRunStore(),adapters,maxConcurrentRuns:1,bodyLimit:100,corsOrigin:"https://app.test"});expect((await api.inject({method:"GET",url:"/v1/health"})).statusCode).toBe(401);const bad=await api.inject(req("POST","/v1/runs",{payload:{}}));expect(bad.statusCode).toBe(400);expect(bad.json().error).toMatchObject({code:"VALIDATION_ERROR"});const huge=await api.inject(req("POST","/v1/runs",{payload:{sessionId:"s1",input:"x".repeat(200)}}));expect(huge.statusCode).toBe(413);});
 it("creates asynchronous idempotent runs, gets status and never exposes transaction secrets",async()=>{const store=new MemoryRunStore();const api=createAgentApi({authenticate:auth,runtime,store,adapters});const a=await api.inject(req("POST","/v1/runs",{headers:{"idempotency-key":"k"},payload:{sessionId:"s1",input:"hi"}}));expect(a.statusCode).toBe(202);const b=await api.inject(req("POST","/v1/runs",{headers:{"idempotency-key":"k"},payload:{sessionId:"s1",input:"hi"}}));expect(b.json().id).toBe(a.json().id);await new Promise(r=>setTimeout(r,0));const got=await api.inject(req("GET",`/v1/runs/${a.json().id}`));expect(got.json().status).toBe("completed");expect(got.body).not.toContain("secret");});
 it("streams retained SSE events and resumes after Last-Event-ID",async()=>{const store=new MemoryRunStore(2);const api=createAgentApi({authenticate:auth,runtime,store,adapters});const made=await api.inject(req("POST","/v1/runs",{payload:{sessionId:"s1",input:"hi"}}));await new Promise(r=>setTimeout(r,0));const events=await api.inject(req("GET",`/v1/runs/${made.json().id}/events`));expect(events.headers["content-type"]).toContain("text/event-stream");expect(events.body).toContain("event: completed");expect(events.body).not.toContain("rawTransaction");const resumed=await api.inject(req("GET",`/v1/runs/${made.json().id}/events`,{headers:{"last-event-id":"1"}}));expect(resumed.body).not.toContain("id: 1\n");});
 it("cancels and exposes tenant sessions, search, approvals, CORS and detailed health",async()=>{const api=createAgentApi({authenticate:auth,runtime,store:new MemoryRunStore(),adapters,corsOrigin:"https://app.test"});expect((await api.inject(req("GET","/v1/sessions/s1"))).json().id).toBe("s1");expect((await api.inject(req("GET","/v1/sessions/search?q=one"))).json().items).toHaveLength(1);expect((await api.inject(req("POST","/v1/approvals/a1/approve"))).json().status).toBe("approved");expect((await api.inject(req("POST","/v1/approvals/a1/deny"))).json().status).toBe("denied");const h=await api.inject(req("GET","/v1/health",{headers:{origin:"https://app.test"}}));expect(h.json()).toMatchObject({status:"ok",dependencies:{runtime:{status:"ok"}}});expect(h.headers["access-control-allow-origin"]).toBe("https://app.test");});
 it("requires decision scope and cancellation scope plus creator ownership unless admin",async()=>{const store=new MemoryRunStore();const api=createAgentApi({authenticate:auth,runtime,store,adapters});const made=await api.inject(req("POST","/v1/runs",{payload:{sessionId:"s1",input:"hi"}}));const id=made.json().id;expect((await api.inject(req("POST","/v1/approvals/a1/approve",{headers:{authorization:"Bearer admin"}}))).statusCode).toBe(403);expect((await api.inject(req("POST",`/v1/runs/${id}/cancel`,{headers:{authorization:"Bearer other"}}))).statusCode).toBe(403);expect((await api.inject(req("POST",`/v1/runs/${id}/cancel`,{headers:{authorization:"Bearer admin"}}))).statusCode).toBe(200)});
});
