import { describe, expect, it, vi } from "vitest";
import { createHash, createHmac } from "node:crypto";
import { parseTransaction } from "viem";
import { buildSimulationRequest, createSimulationEvidence } from "../src/execution/simulation.js";
import { keccak256 } from "viem";
import { AuthorizationIssuer, InMemoryReplayStore, SignerWireVerifier, type AuthorizationChecks } from "../src/execution/authorization/index.js";
import { ExecutionGateway } from "../src/execution/gateway.js";

const tx={chainId:46630,from:"0x0000000000000000000000000000000000000001" as const,to:"0x0000000000000000000000000000000000000002" as const,data:"0x12345678" as const,value:0n,gas:100000n,nonce:7,type:"eip1559" as const,maxFeePerGas:20n,maxPriorityFeePerGas:2n,accessList:[]};
const hexHash=(s:string)=>`0x${createHash("sha256").update(s).digest("hex")}`;
const key="test-only-mac-key";
const signer={sign:async(data:string)=>createHmac("sha256",key).update(data).digest("hex")};
const verifier={verify:async(data:string,signature:string)=>createHmac("sha256",key).update(data).digest("hex")===signature};
const refs={quoteHash:hexHash("quote"),policyHash:hexHash("policy"),riskHash:hexHash("risk"),reservationId:"reserve-1",approvalId:"approve-1",audience:"signer-prod",signerKeyId:"key-1"};
const simulation={success:true,blockNumber:100n,blockHash:hexHash("block"),transactionHash:"" as `0x${string}`,gasUsed:54321n,stateDiffs:[{address:tx.to,key:"0x01",before:"0x00",after:"0x02"}],events:[{address:tx.to,topics:[hexHash("topic")],data:"0xab"}],assetDeltas:[{asset:tx.to,amount:-2n}]};
function setup(now=1_000_000){
 const request=buildSimulationRequest(tx,refs.policyHash); simulation.transactionHash=request.transactionHash;
 const evidence=createSimulationEvidence(request,simulation);
 const checks:AuthorizationChecks={quote:async h=>h===refs.quoteHash,policy:async h=>h===refs.policyHash,risk:async h=>h===refs.riskHash,reservation:async id=>id===refs.reservationId,approval:async id=>id===refs.approvalId,simulation:async h=>h===evidence.hash,nonce:async()=>tx.nonce};
 const issuer=new AuthorizationIssuer({checks,signer,now:()=>now,ttlMs:5000});
 return {request,evidence,issuer,now};
}

describe("simulation authorization envelope",()=>{
 it("hashes pinned block/hash, state diffs, events, gas and deltas as evidence",()=>{const {request}=setup();const a=createSimulationEvidence(request,simulation);const changed=createSimulationEvidence(request,{...simulation,gasUsed:simulation.gasUsed+1n});expect(a.hash).not.toBe(changed.hash);expect(a.blockHash).toBe(simulation.blockHash)});
 it("issues a short-lived envelope only after every current check passes",async()=>{const {request,evidence,issuer,now}=setup();const envelope=await issuer.issue(request,evidence,refs);expect(envelope.claims).toMatchObject({chainId:tx.chainId,account:tx.from,nonce:tx.nonce,transactionHash:request.transactionHash,policyHash:refs.policyHash,simulationHash:evidence.hash,approvalId:refs.approvalId,reservationId:refs.reservationId,audience:refs.audience,expiresAt:now+5000});expect(envelope.signature).toBeTruthy()});
 it("fails closed when quote, policy, risk, reservation, approval, simulation, or nonce is no longer current",async()=>{const {request,evidence}=setup();for(const name of ["quote","policy","risk","reservation","approval","simulation","nonce"] as const){const good=setup().issuer;const checks=(good as any).dependencies.checks as AuthorizationChecks;(checks[name] as any)=async()=>false;await expect(good.issue(request,evidence,refs)).rejects.toThrow(`authorization_${name}_invalid`)}});
 it("wire verifier independently decodes bytes and rejects transaction/envelope mismatch",async()=>{const {request,evidence,issuer}=setup();const envelope=await issuer.issue(request,evidence,refs);const wire=new SignerWireVerifier({verifier,replayStore:new InMemoryReplayStore(),now:()=>1_000_001,audience:refs.audience});const altered=buildSimulationRequest({...tx,nonce:8},refs.policyHash);await expect(wire.verify(altered.serialized,envelope)).rejects.toThrow("envelope_transaction_mismatch");expect(parseTransaction((await wire.verify(request.serialized,envelope)).serialized).nonce).toBe(tx.nonce)});
 it("rejects expiry, wrong audience, bad MAC, and replay",async()=>{const {request,evidence,issuer}=setup();const envelope=await issuer.issue(request,evidence,refs);await expect(new SignerWireVerifier({verifier,replayStore:new InMemoryReplayStore(),now:()=>envelope.claims.expiresAt,audience:refs.audience}).verify(request.serialized,envelope)).rejects.toThrow("envelope_expired");await expect(new SignerWireVerifier({verifier,replayStore:new InMemoryReplayStore(),now:()=>1_000_001,audience:"other"}).verify(request.serialized,envelope)).rejects.toThrow("envelope_audience_mismatch");await expect(new SignerWireVerifier({verifier,replayStore:new InMemoryReplayStore(),now:()=>1_000_001,audience:refs.audience}).verify(request.serialized,{...envelope,signature:"bad"})).rejects.toThrow("envelope_signature_invalid");const wire=new SignerWireVerifier({verifier,replayStore:new InMemoryReplayStore(),now:()=>1_000_001,audience:refs.audience});await wire.verify(request.serialized,envelope);await expect(wire.verify(request.serialized,envelope)).rejects.toThrow("envelope_replayed")});
 it("gateway production execute accepts envelope plus exact bytes, never a raw prepared transaction, and does not reserialize",async()=>{const {request,evidence,issuer}=setup();const envelope=await issuer.issue(request,evidence,refs);const sign=vi.fn(async(bytes:`0x${string}`)=>bytes);const expected=keccak256(request.serialized);const gateway=new ExecutionGateway({simulate:async()=>simulation,wireVerifier:new SignerWireVerifier({verifier,replayStore:new InMemoryReplayStore(),now:()=>1_000_001,audience:refs.audience}),signSerialized:sign,broadcast:async()=>expected});const result=await gateway.execute({serialized:request.serialized,envelope});expect(result.hash).toBe(expected);expect(sign).toHaveBeenCalledWith(request.serialized);await expect((gateway.execute as any)(tx,{policyHash:refs.policyHash})).rejects.toThrow()});
 it.each(["0xsent","0x"+"f".repeat(64)])("moves malformed or mismatched broadcaster hashes to reconciliation",async hash=>{const {request,evidence,issuer}=setup();const envelope=await issuer.issue(request,evidence,refs);const replay=new InMemoryReplayStore();const gateway=new ExecutionGateway({simulate:async()=>simulation,wireVerifier:new SignerWireVerifier({verifier,replayStore:replay,now:()=>1_000_001,audience:refs.audience}),signSerialized:async b=>b,broadcast:async()=>hash as `0x${string}`});await expect(gateway.execute({serialized:request.serialized,envelope})).rejects.toThrow(/broadcast_hash/);expect(replay.states.get(envelope.claims.id)).toBe("reconciliation")});
 it("binds every transaction field and signer identity in signed claims",async()=>{const {request,evidence,issuer}=setup();const envelope=await issuer.issue(request,evidence,refs);expect(envelope.claims).toMatchObject({protocol:"robinhood-execution-authorization",version:1,signerKeyId:"key-1",serialized:request.serialized,to:tx.to,data:tx.data,value:"0",gas:"100000",type:"eip1559",maxFeePerGas:"20",maxPriorityFeePerGas:"2",accessList:[]});const wire=new SignerWireVerifier({verifier,replayStore:new InMemoryReplayStore(),now:()=>1_000_001,audience:refs.audience,signerKeyId:"wrong",nonce:async()=>tx.nonce});await expect(wire.verify(request.serialized,envelope)).rejects.toThrow("envelope_signer_mismatch")});
 it("recomputes evidence, rejects unsafe TTL, future issue time and nonce TOCTOU",async()=>{const {request,evidence}=setup();await expect(new AuthorizationIssuer({checks:(setup().issuer as any).dependencies.checks,signer,now:()=>1,ttlMs:0}).issue(request,evidence,refs)).rejects.toThrow("authorization_ttl_invalid");await expect(setup().issuer.issue(request,{...evidence,gasUsed:evidence.gasUsed+1n},refs)).rejects.toThrow("authorization_simulation_invalid");const envelope=await setup().issuer.issue(request,evidence,refs);await expect(new SignerWireVerifier({verifier,replayStore:new InMemoryReplayStore(),now:()=>999_999,audience:refs.audience,signerKeyId:refs.signerKeyId,nonce:async()=>tx.nonce}).verify(request.serialized,envelope)).rejects.toThrow("envelope_issued_in_future");await expect(new SignerWireVerifier({verifier,replayStore:new InMemoryReplayStore(),now:()=>1_000_001,audience:refs.audience,signerKeyId:refs.signerKeyId,nonce:async()=>tx.nonce+1}).verify(request.serialized,envelope)).rejects.toThrow("envelope_nonce_changed")});
});
