import {afterEach,describe,expect,it,vi} from 'vitest';
import {chmodSync,closeSync,mkdtempSync,openSync,rmSync,writeFileSync} from 'node:fs';
import {createServer} from 'node:net';import {join} from 'node:path';import {tmpdir} from 'node:os';import {createHash} from 'node:crypto';
import {loadConfig,sanitizedConfig} from '../src/config/index.js';import {createApplication,createTradingComposition} from '../src/app/index.js';import {createStandaloneServer} from '../src/server.js';import {encodeAbiParameters} from 'viem';
import {ApprovalEngine} from '../src/execution/approvals/index.js';
import {AuthorizationIssuer} from '../src/execution/authorization/index.js';
import {ProductionRiskEvaluator,ReservationLedger} from '../src/execution/control/index.js';
const dirs:string[]=[];const temp=()=>{const d=mkdtempSync(join(tmpdir(),'live-compose-'));dirs.push(d);return d};afterEach(()=>dirs.splice(0).forEach(d=>rmSync(d,{recursive:true,force:true})));
const A='0x0000000000000000000000000000000000000001',B='0x0000000000000000000000000000000000000002';
function liveEnv(d:string){const token=join(d,'signer.token'),policy=join(d,'policy.json'),operator=join(d,'operator.key'),authorization=join(d,'authorization.key'),socket=join(d,'signer.sock');for(const [path,value] of [[token,'secret'],[policy,'{}'],[operator,'operator-secret'],[authorization,'authorization-secret']] as const)writeFileSync(path,value,{mode:0o600});return {NODE_ENV:'test',DATA_DIR:d,NETWORK:'mainnet',CHAIN_ID:'4663',RPC_URL:'http://127.0.0.1:8545',EXECUTION_MODE:'live',MAINNET_ENABLED:'true',MAINNET_ACKNOWLEDGE_RISK:'I_ACKNOWLEDGE_MAINNET_RISK',LIVE_TRADING_ENABLED:'true',LIVE_TRADING_ACKNOWLEDGE_RISK:'I_ACKNOWLEDGE_LIVE_TRADING_RISK',TRADING_ACCOUNT:A,SIGNER_SOCKET_PATH:socket,SIGNER_TOKEN_PATH:token,SIGNER_POLICY_PATH:policy,APPROVAL_OPERATOR_IDS:'operator',APPROVAL_OPERATOR_KEY_IDS:'operator-v1',APPROVAL_OPERATOR_KEY_PATHS:operator,AUTHORIZATION_KEY_ID:'authorization-v1',AUTHORIZATION_KEY_PATH:authorization,TRADING_MAX_AMOUNT_IN:'1000',TRADING_ALLOWED_TOKENS:`${A},${B}`,TRADING_MAX_SLIPPAGE_BPS:'100',TRADING_FINALITY_BLOCKS:'2',API_BEARER_TOKEN:'api',API_SCOPES:'tool:read,tool:invoke,trading:quote,trading:execute'} as const}
async function signerStatus(env:ReturnType<typeof liveEnv>,overrides:Record<string,unknown>={}){const policyRaw='{}',status={account:A,chainIds:[4663],policyHash:`0x${createHash('sha256').update(policyRaw).digest('hex')}`,policyVersion:1,authorizationKeyId:'authorization-v1',serviceVersion:'0.1.0',...overrides};const server=createServer(c=>{let data='';c.on('data',b=>{data+=b;if(data.includes('\n'))c.end(JSON.stringify({ok:true,result:status})+'\n')})});await new Promise<void>(r=>server.listen(env.SIGNER_SOCKET_PATH,r));return server}
describe('live trading configuration and production composition',()=>{
 it('injects every mandatory funded execution control into the shipped live composition',()=>{const d=temp(),composition=createTradingComposition(loadConfig(liveEnv(d)))!;expect(composition.approvals).toBeInstanceOf(ApprovalEngine);expect(composition.authorization).toBeInstanceOf(AuthorizationIssuer);expect(composition.reservations).toBeInstanceOf(ReservationLedger);expect(composition.riskEvaluator).toBeInstanceOf(ProductionRiskEvaluator);expect(composition.risk).toBeDefined();expect((composition.authorization as any).signerKeyId).toBe('authorization-v1');composition.close()});
 it('evaluates production risk against configured limits and durable tokenIn reservations',async()=>{const d=temp(),composition=createTradingComposition(loadConfig(liveEnv(d)))!,risk=composition.risk!;const now=BigInt(Math.floor(Date.now()/1000)),base={now,chain:4663n,account:A,router:composition.riskEvaluator!.limits.routers[0]!,tokenIn:A,tokenOut:B,amountIn:100n,slippageBps:50n,quoteAt:now,quoteBlock:10n,currentBlock:10n,quoteBlockHash:'h',canonicalBlockHash:'h',tokenBalance:1000n,nativeBalance:1000n,estimatedGasCost:1n};expect(await risk.assess(base)).toMatchObject({allowed:true,reasons:[]});for(const [change,reason] of [[{amountIn:1001n},'per_trade_limit_exceeded'],[{router:B},'router_not_allowed'],[{tokenOut:'0x0000000000000000000000000000000000000003'},'token_not_allowed'],[{quoteAt:now-31n},'quote_stale'],[{tokenBalance:99n},'insufficient_token_balance'],[{nativeBalance:1n},'insufficient_gas_reserve']] as const){const result:any=await risk.assess({...base,...change});expect(result.allowed).toBe(false);expect(result.reasons).toContain(reason)}expect(composition.reservations!.reserve({id:'existing',at:now,asset:A,strategy:'live',amount:950n})).toBe(true);expect((await risk.assess(base)).reasons).toContain('token_reserved_exposure_exceeded');composition.close()});
 it('constructs and simulates one exact unsigned transaction at the quoted block',async()=>{const d=temp(),calls:string[]=[];const fetch=vi.fn(async(_u:any,init:any)=>{const x=JSON.parse(init.body);calls.push(x.method);const H=`0x${'11'.repeat(32)}`;let result:any;if(x.method==='eth_blockNumber')result='0xa';else if(x.method==='eth_getBlockByNumber'||x.method==='eth_getBlockByHash')result={number:'0xa',hash:H,parentHash:`0x${'22'.repeat(32)}`,timestamp:'0x1',transactions:[],baseFeePerGas:'0x5'};else if(x.method==='eth_getTransactionCount')result='0x7';else if(x.method==='eth_maxPriorityFeePerGas')result='0x2';else if(x.method==='eth_estimateGas')result='0x186a0';else if(x.method==='eth_call')result=x.params[0]?.to?.toLowerCase()==='0x33e885ed0ec9bf04ecfb19341582aadcb4c8a9e7'?encodeAbiParameters([{type:'uint256'},{type:'uint160'},{type:'uint32'},{type:'uint256'}],[100n,1n,0,100000n]):'0x';else if(x.method==='debug_traceCall')result={gasUsed:'0x15f90',logs:[]};else if(x.method==='eth_chainId')result='0x1237';else if(x.method==='eth_getCode')result='0x12';else result='0x0';return new Response(JSON.stringify({jsonrpc:'2.0',id:x.id,result}),{headers:{'content-type':'application/json'}})});const app=createApplication(loadConfig({...liveEnv(d),EXECUTION_MODE:'dry-run',LIVE_TRADING_ENABLED:'false',LIVE_TRADING_ACKNOWLEDGE_RISK:undefined} as any),{rpcFetch:fetch as any});const q=await app.trading!.quote({side:'buy',tokenIn:A,tokenOut:B,amountIn:10n,slippageBps:50});expect(q.request?.serialized).toMatch(/^0x/);expect(q.evidence?.transactionHash).toBe(q.request?.transactionHash);expect(q.blockHash).toBe(`0x${'11'.repeat(32)}`);expect(calls).toContain('eth_getTransactionCount');await app.stop()});
 it('supports read-only and dry-run but requires the complete mainnet live triple opt-in',()=>{const d=temp();expect(loadConfig({NODE_ENV:'test',DATA_DIR:d,EXECUTION_MODE:'dry-run'}).execution).toBe('dry-run');expect(()=>loadConfig({...liveEnv(d),LIVE_TRADING_ENABLED:'false'})).toThrow(/triple opt-in/i);expect(loadConfig(liveEnv(d)).trading?.account).toBe(A);expect(sanitizedConfig(loadConfig(liveEnv(d)))).not.toHaveProperty('trading.signerTokenPath')});
 it('requires RPC and absolute private regular signer files',()=>{const d=temp(),e:any=liveEnv(d);delete e.RPC_URL;expect(()=>loadConfig(e)).toThrow(/RPC_URL/);expect(()=>loadConfig({...liveEnv(d),SIGNER_SOCKET_PATH:'relative.sock'})).toThrow(/absolute/);chmodSync(e.SIGNER_TOKEN_PATH,0o644);expect(()=>loadConfig(e)).toThrow(/permissions/)});
 it('registers trading only when configured and reports signer readiness honestly',async()=>{const d=temp();const absent=createApplication(loadConfig({NODE_ENV:'test',DATA_DIR:d}));expect(absent.registry.listPrivileged().some(x=>x.name.startsWith('trade.'))).toBe(false);await absent.stop();const fetch=vi.fn(async(_u:any,init:any)=>{const x=JSON.parse(init.body);let result:any=x.method==='eth_chainId'?'0x1237':x.method==='eth_getCode'?'0x12':x.method==='eth_blockNumber'?'0x10':'0x0';return new Response(JSON.stringify({jsonrpc:'2.0',id:x.id,result}),{headers:{'content-type':'application/json'}})});const app=createApplication(loadConfig(liveEnv(d)),{rpcFetch:fetch as any});await app.start();expect(app.registry.listPrivileged().map(x=>x.name)).toContain('trade.buy');expect((await app.health()).dependencies.trading.status).toBe('unhealthy');expect(app.ready()).toBe(false);await app.stop()});
 it('fails readiness with an explicit nonsecret signer identity mismatch',async()=>{const d=temp(),env=liveEnv(d),server=await signerStatus(env,{authorizationKeyId:'wrong-key'});const fetch=vi.fn(async(_u:any,init:any)=>{const x=JSON.parse(init.body);const result=x.method==='eth_chainId'?'0x1237':x.method==='eth_getCode'?'0x12':'0x10';return new Response(JSON.stringify({jsonrpc:'2.0',id:x.id,result}))});const composition=createTradingComposition(loadConfig(env),fetch as any)!;await expect(composition.verify()).rejects.toThrow('signer_authorization_key_id_mismatch');composition.close();await new Promise<void>(r=>server.close(()=>r()))});
 it('mounts authenticated trading API on the shipped server',async()=>{const d=temp();const s=await createStandaloneServer(loadConfig({...liveEnv(d),EXECUTION_MODE:'dry-run',LIVE_TRADING_ENABLED:'false',LIVE_TRADING_ACKNOWLEDGE_RISK:undefined} as any),{rpcFetch:vi.fn(async()=>{throw Error('offline')}) as any});expect((await s.inject({method:'POST',url:'/v1/trading/quote',payload:{}})).statusCode).toBe(401);expect((await s.inject({method:'POST',url:'/v1/trading/quote',headers:{authorization:'Bearer api'},payload:{}})).statusCode).not.toBe(404);await s.close()});
});
