import {describe,it,expect} from 'vitest';
import {encodeErrorResult} from 'viem';
import {RpcSimulator,RpcSimulationError,decodeRevertData} from '../src/execution/rpc-simulator.js';
const H='0x'+'11'.repeat(32), P='0x'+'22'.repeat(32), TO='0x'+'33'.repeat(20), FROM='0x'+'44'.repeat(20);
const req:any={transaction:{chainId:46630,from:FROM,to:TO,data:'0x12345678',value:0n,gas:100000n,nonce:1},serialized:'0x01',transactionHash:H,policyHash:'policy'};
function rpc(handler:(m:string,p:any[])=>unknown):typeof fetch{return (async (_u:URL|RequestInfo,i?:RequestInit)=>{const b=JSON.parse(String(i?.body));const result=handler(b.method,b.params);return new Response(JSON.stringify({jsonrpc:'2.0',id:b.id,...(result instanceof Error?{error:{code:3,message:result.message,data:(result as any).data}}:{result})}))}) as typeof fetch}
describe('RpcSimulator',()=>{
it('pins chain and block, calls exact tx, estimates gas and traces with provenance',async()=>{const calls:any[]=[];const fetch=rpc((m,p)=>{calls.push([m,p]);if(m==='eth_chainId')return '0xb626';if(m==='eth_getBlockByNumber'||m==='eth_getBlockByHash')return {number:'0x10',hash:H,parentHash:P};if(m==='eth_call')return '0x';if(m==='eth_estimateGas')return '0x5208';if(m==='debug_traceCall')return {gas:'0x5208',logs:[],stateDiffs:[],assetDeltas:[]};throw Error(m)});const r=await new RpcSimulator({url:'https://user:secret@rpc.test',chainId:46630,fetch}).simulate(req);expect(r).toMatchObject({success:true,blockNumber:16n,blockHash:H,gasUsed:21000n,assetDeltas:[]});expect(r.provenance.url).toBe('https://rpc.test/');expect(calls.some(x=>x[0]==='eth_call'&&x[1][1].blockHash===H)).toBe(true)});
it('decodes revert and fails closed when trace is required but unavailable',async()=>{const reason=encodeErrorResult({abi:[{type:'error',name:'Error',inputs:[{type:'string'}]}],errorName:'Error',args:['oops']});expect(decodeRevertData(reason)).toContain('oops');const fetch=rpc((m)=>m==='eth_chainId'?'0xb626':m.startsWith('eth_getBlock')?{number:'0x10',hash:H,parentHash:P}:m==='eth_call'?'0x':m==='eth_estimateGas'?'0x1':new Error('method not found'));await expect(new RpcSimulator({url:'http://rpc',chainId:46630,fetch,requireTrace:true}).simulate(req)).rejects.toMatchObject({code:'trace_unavailable'})});
it('rejects chain mismatch and oversized responses',async()=>{const fetch=rpc(m=>m==='eth_chainId'?'0x1':'x'.repeat(1000));await expect(new RpcSimulator({url:'http://rpc',chainId:46630,fetch,maxResponseBytes:100}).simulate(req)).rejects.toBeInstanceOf(RpcSimulationError)})});
