import {describe,it,expect,vi} from 'vitest';
import {decodeFunctionData,getAddress,encodeEventTopics,encodeAbiParameters} from 'viem';
import {UNISWAP_V3_ROUTER_ABI,WETH_ABI,discoverPools,buildRoutedSwapIntent,buildSwapTransaction,approvalPlan,preflightAllowance,quoteRoutesAtBlock,decodeSwapReceipt,positionDeltas,validateNoxaTrade,createRobinhoodTradingClient} from '../src/trading/index.js';
const a=(n:number)=>getAddress(`0x${n.toString(16).padStart(40,'0')}`); const A=a(1),B=a(2),C=a(3),O=a(4),R=a(5),F=a(6),Q=a(7),W=a(8);
describe('production deterministic trading',()=>{
 it('discovers only verified, liquid factory pools at a pinned block',async()=>{const readContract=vi.fn(async(x:any)=>x.functionName==='getPool'?(x.args[2]===500?a(50):a(0)):x.functionName==='factory'?F:x.functionName==='token0'?A:x.functionName==='token1'?B:x.functionName==='fee'?500:1n);const pools=await discoverPools({readContract,getCode:async()=> '0x12'} as any,{factory:F,tokenA:A,tokenB:B,feeTiers:[100,500,3000],blockNumber:12n});expect(pools).toEqual([{token0:A,token1:B,fee:500,pool:a(50),liquidity:1n}]);expect(readContract.mock.calls[0]![0].blockNumber).toBe(12n)});
 it('encodes exactInput for multihop and exactInputSingle for one hop',()=>{const multi=buildRoutedSwapIntent({chainId:4663,owner:O,router:R,recipient:O,path:{tokens:[A,C,B],fees:[500,3000]},amountIn:10n,quotedAmountOut:20n,now:1n});const tx=buildSwapTransaction(multi,{nonce:1,gas:1n,maxFeePerGas:2n,maxPriorityFeePerGas:1n});expect(decodeFunctionData({abi:UNISWAP_V3_ROUTER_ABI,data:tx.transaction.data}).functionName).toBe('exactInput');expect(multi.slippageBps).toBe(100);expect(multi.deadline).toBe(301n)});
 it('fails closed for native input until exact multicall semantics are implemented',()=>{expect(()=>buildRoutedSwapIntent({chainId:4663,owner:O,router:R,recipient:O,path:{tokens:[W,B],fees:[500]},amountIn:10n,quotedAmountOut:20n,now:1n,nativeInput:true,weth:W})).toThrow(/native input disabled/)});
 it('uses exact approvals, zero-reset, revoke and fail-closed allowance preflight',async()=>{expect(approvalPlan({chainId:4663,owner:O,token:A,spender:R,currentAllowance:5n,requiredAmount:9n,zeroReset:true}).map(x=>x.amount)).toEqual([0n,9n]);await expect(preflightAllowance({readContract:async()=>8n} as any,{owner:O,token:A,spender:R,requiredAmount:9n})).rejects.toThrow(/allowance/)});
 it('quotes all routes at one pinned block and returns evidence',async()=>{const c:any={getBlockNumber:async()=>44n,readContract:async(x:any)=>x.functionName==='quoteExactInputSingle'?[x.args[0].fee===500?9n:8n,0n,0,1n]:[7n,[],[],1n]};const r=await quoteRoutesAtBlock(c,{quoter:Q,paths:[{tokens:[A,B],fees:[500]},{tokens:[A,B],fees:[3000]}],amountIn:1n});expect(r.blockNumber).toBe(44n);expect(r.best.amountOut).toBe(9n);expect(r.quotes.every(x=>x.blockNumber===44n)).toBe(true)});
 it('decodes transfer deltas but does not mislabel swap flow as P&L',()=>{const transfer={type:'event',name:'Transfer',inputs:[{indexed:true,name:'from',type:'address'},{indexed:true,name:'to',type:'address'},{indexed:false,name:'value',type:'uint256'}]} as const;const log=(token:any,from:any,to:any,value:bigint)=>({address:token,topics:encodeEventTopics({abi:[transfer],eventName:'Transfer',args:{from,to}}),data:encodeAbiParameters([{type:'uint256'}],[value])});const r=decodeSwapReceipt({transactionHash:`0x${'1'.repeat(64)}`,blockNumber:3n,status:'success',gasUsed:10n,effectiveGasPrice:2n,logs:[log(A,O,R,5n),log(B,R,O,7n)]} as any,O);expect(r.deltas).toEqual([{token:A,delta:-5n},{token:B,delta:7n}]);expect(positionDeltas(r.deltas,{[A]:2n,[B]:3n})).toMatchObject({pnl:null})});
 it('enforces verified NOXA record, pair/pool/fee and restriction block',()=>{const record:any={exists:true,token:B,pairedToken:A,poolFee:500,restrictionsEndBlock:10n};expect(()=>validateNoxaTrade({token:B,path:{tokens:[A,B],fees:[500]},blockNumber:9n,record})).toThrow(/restricted/);expect(validateNoxaTrade({token:B,path:{tokens:[A,B],fees:[500]},blockNumber:10n,record}).verified).toBe(true)});
 it('creates only chain-4663 clients and verifies configured contract bytecode',async()=>{await expect(createRobinhoodTradingClient({client:{getChainId:async()=>1,getCode:async()=> '0x12'} as any})).rejects.toThrow(/chain/)});
});
