import { createHash, randomUUID } from "node:crypto";
import { mkdir, mkdtemp, open, rename, rm } from "node:fs/promises";
import { tmpdir } from "node:os";
import { dirname, isAbsolute, join } from "node:path";
import { z } from "zod";

const safePath=z.string().min(1).refine(p=>!isAbsolute(p)&&!p.includes("\\")&&!p.split("/").some(x=>!x||x==="."||x===".."),"invalid scoped path");
const cap=z.string().regex(/^[a-z][a-z0-9_.-]{0,63}$/).refine(x=>!/(^|[._-])(signing?|wallet|broadcast|raw.?transaction|policy|approval|memory|skills?|jobs?)([._-]|$)/i.test(x),"forbidden capability");
const schema=z.object({schemaVersion:z.literal(1),id:z.string().regex(/^[a-z0-9]+(?:[.-][a-z0-9]+)+$/).max(128),version:z.string().regex(/^\d+\.\d+\.\d+(?:-[0-9A-Za-z.-]+)?$/),package:z.object({sha256:z.string().regex(/^[a-f0-9]{64}$/),provenance:z.string().url().max(2048)}).strict(),compatibility:z.object({agent:z.string().min(1).max(128),node:z.string().min(1).max(128)}).strict(),tools:z.array(z.object({name:z.string().regex(/^[a-z][a-z0-9_.-]{0,63}$/),effect:z.enum(["read","write","external"]),capabilities:z.array(cap).min(1).max(32)}).strict()).min(1).max(64),permissions:z.object({filesystem:z.object({read:z.array(safePath).max(64),write:z.array(safePath).max(64)}).strict(),network:z.array(z.object({hostname:z.string().regex(/^(?=.{1,253}$)(?:[a-z0-9](?:[a-z0-9-]{0,61}[a-z0-9])?\.)*[a-z0-9](?:[a-z0-9-]{0,61}[a-z0-9])?$/),port:z.number().int().min(1).max(65535),tls:z.literal(true)}).strict()).max(64),env:z.array(z.string().regex(/^[A-Z_][A-Z0-9_]{0,127}$/)).max(64)}).strict(),resources:z.object({cpuMs:z.number().int().positive().max(3_600_000),memoryMb:z.number().int().positive().max(4096),timeoutMs:z.number().int().positive().max(3_600_000)}).strict()}).strict();
export type PluginManifest=z.infer<typeof schema>;
const freeze=<T>(x:T):T=>{if(x&&typeof x==="object"){for(const v of Object.values(x as object))freeze(v);Object.freeze(x)}return x};
export function parsePluginManifest(input:unknown):PluginManifest { const r=schema.safeParse(input);if(!r.success)throw new Error(`Invalid/unknown/forbidden plugin manifest: ${r.error.issues.map(x=>`${x.path.join(".")}: ${x.message}`).join(", ")}`);return freeze(r.data) }
function ordered(x:unknown):unknown {if(Array.isArray(x))return x.map(ordered);if(x&&typeof x==="object")return Object.fromEntries(Object.entries(x).sort(([a],[b])=>a.localeCompare(b)).map(([k,v])=>[k,ordered(v)]));return x}
export function canonicalManifest(input:unknown){return JSON.stringify(ordered(parsePluginManifest(input)))}
export interface ArchiveEntry {path:string;data:Buffer;type?:"file"|"symlink"|"directory"}
export class PluginInstaller { constructor(private o:{root:string;verifySignature:(payload:Buffer,signature:Buffer)=>boolean|Promise<boolean>;limits?:{maxFiles:number;maxUnpackedBytes:number}}){} async install(i:{manifest:unknown;signature:Buffer;packageBytes:Buffer;entries:ArchiveEntry[]}){const m=parsePluginManifest(i.manifest);if(!await this.o.verifySignature(Buffer.from(canonicalManifest(m)),i.signature))throw new Error("Invalid plugin signature");if(createHash("sha256").update(i.packageBytes).digest("hex")!==m.package.sha256)throw new Error("Package digest mismatch");const lim=this.o.limits??{maxFiles:1024,maxUnpackedBytes:100*1024*1024};if(i.entries.length>lim.maxFiles)throw new Error("Archive file limit exceeded");let size=0;for(const e of i.entries){if(e.type&&e.type!=="file"&&e.type!=="directory")throw new Error("Archive symlink rejected");if(e.type!=="directory")size+=e.data.length;if(size>lim.maxUnpackedBytes)throw new Error("Archive size limit exceeded");safePath.parse(e.path)}const target=join(this.o.root,m.id,m.version),stage=`${target}.tmp-${randomUUID()}`;await mkdir(stage,{recursive:true});try{for(const e of i.entries){const p=join(stage,e.path);if(e.type==="directory")await mkdir(p,{recursive:true});else{await mkdir(dirname(p),{recursive:true});const h=await open(p,"wx",0o600);try{await h.writeFile(e.data)}finally{await h.close()}}}await mkdir(dirname(target),{recursive:true});await rename(stage,target)}catch(e){await rm(stage,{recursive:true,force:true});throw e}return{id:m.id,version:m.version,path:target,checksum:m.package.sha256}}}

export interface PluginWorker {invoke(tool:string,input:unknown,signal?:AbortSignal):Promise<unknown>;terminate():Promise<void>|void}
type Request={capability:string;operation:string;input:unknown};
export class PluginHost {private crashes=new Map<string,number>();constructor(private o:{spawn:(options:{manifest:PluginManifest;env:Record<string,string>;cwd:string;resources:PluginManifest["resources"]})=>Promise<PluginWorker>;env?:Record<string,string|undefined>;mediate:(request:Request,manifest:PluginManifest)=>Promise<unknown>;quarantineThreshold?:number}){}isQuarantined(id:string){return(this.crashes.get(id)??0)>=(this.o.quarantineThreshold??3)}async start(m:PluginManifest){if(this.isQuarantined(m.id))throw new Error("Plugin quarantined");const cwd=await mkdtemp(join(tmpdir(),"plugin-")),env:Record<string,string>={};for(const n of m.permissions.env){const v=(this.o.env??process.env)[n];if(v!==undefined)env[n]=v}const worker=await this.o.spawn({manifest:m,env,cwd,resources:m.resources});const allowed=new Set(m.tools.flatMap(t=>t.capabilities));const crash=()=>this.crashes.set(m.id,(this.crashes.get(m.id)??0)+1);return{request:(r:Request)=>{if(!allowed.has(r.capability))return Promise.reject(new Error("Capability denied"));return this.o.mediate(r,m)},invoke:async(tool:string,input:unknown,signal?:AbortSignal)=>{if(!m.tools.some(t=>t.name===tool))throw new Error("Capability/tool denied");const c=new AbortController(),timer=setTimeout(()=>c.abort(new Error("Plugin timeout")),m.resources.timeoutMs),abort=()=>c.abort(signal?.reason);signal?.addEventListener("abort",abort,{once:true});try{return await Promise.race([worker.invoke(tool,input,c.signal),new Promise((_,reject)=>c.signal.addEventListener("abort",()=>reject(c.signal.reason),{once:true}))])}catch(e){if(!c.signal.aborted)crash();throw e}finally{clearTimeout(timer);signal?.removeEventListener("abort",abort)}},close:async()=>{await worker.terminate();await rm(cwd,{recursive:true,force:true})}}}}
