import { z } from "zod";

export type Source = "blockscout"|"dexscreener"|"geckoterminal";
export class IntelligenceError extends Error {
  constructor(public source:Source, public code:"TIMEOUT"|"RATE_LIMITED"|"HTTP_ERROR"|"INVALID_RESPONSE"|"NETWORK_ERROR", message:string, public status?:number, public retryAfterMs?:number, public cause?:unknown){super(message);this.name="IntelligenceError";}
}
type Options={fetch?:typeof globalThis.fetch;timeoutMs?:number;retries?:number;retryDelayMs?:number};
class HttpClient {
  protected fetchFn:typeof fetch; private timeout:number; private retries:number; private delay:number;
  constructor(protected source:Source, protected baseUrl:string,o:Options={}){this.fetchFn=o.fetch??globalThis.fetch;this.timeout=o.timeoutMs??8_000;this.retries=o.retries??2;this.delay=o.retryDelayMs??100;}
  protected async get<T>(path:string,schema:z.ZodType<T>):Promise<T>{
    for(let attempt=0;;attempt++){const controller=new AbortController();const timer=setTimeout(()=>controller.abort(),this.timeout);
      try {const response=await this.fetchFn(`${this.baseUrl}${path}`,{signal:controller.signal,headers:{accept:"application/json"}});clearTimeout(timer);
        if(!response.ok){const retryAfter=response.headers.get("retry-after");const error=new IntelligenceError(this.source,response.status===429?"RATE_LIMITED":"HTTP_ERROR",`HTTP ${response.status}`,response.status,retryAfter?Number(retryAfter)*1000:undefined);if(attempt<this.retries&&(response.status===429||response.status>=500)){await sleep(this.delay*2**attempt);continue;}throw error;}
        const parsed=schema.safeParse(await response.json());if(!parsed.success)throw new IntelligenceError(this.source,"INVALID_RESPONSE",parsed.error.message,response.status,undefined,parsed.error);return parsed.data;
      } catch(e){clearTimeout(timer);if(e instanceof IntelligenceError)throw e;const timeout=e instanceof DOMException&&e.name==="AbortError";if(attempt<this.retries){await sleep(this.delay*2**attempt);continue;}throw new IntelligenceError(this.source,timeout?"TIMEOUT":"NETWORK_ERROR",timeout?"Request timed out":"Network request failed",undefined,undefined,e);}
    }
  }
}
const sleep=(ms:number)=>new Promise(r=>setTimeout(r,ms)); const numeric=z.union([z.string(),z.number()]).nullable().optional(); const num=(x:unknown)=>x==null?undefined:Number(x);
export interface MarketPair {source:Source;chainId:string;dexId?:string;address:string;baseToken:{address:string;name?:string;symbol?:string};quoteToken:{address:string;name?:string;symbol?:string};priceUsd?:number|undefined;liquidityUsd?:number|undefined;volume24hUsd?:number|undefined;createdAt?:number|undefined;raw:unknown}
const dsToken=z.object({address:z.string(),name:z.string().optional(),symbol:z.string().optional()});
const dsPair=z.object({chainId:z.string(),dexId:z.string().optional(),pairAddress:z.string(),baseToken:dsToken,quoteToken:dsToken,priceUsd:numeric,liquidity:z.object({usd:numeric}).optional(),volume:z.object({h24:numeric}).optional(),pairCreatedAt:z.number().optional()}).passthrough();
const dsResponse=z.object({pairs:z.array(dsPair).nullable().default([])});
export class DexScreenerClient extends HttpClient {constructor(o:Options={}){super("dexscreener","https://api.dexscreener.com",o)} private map(p:z.infer<typeof dsPair>):MarketPair{return {source:"dexscreener",chainId:p.chainId,...(p.dexId?{dexId:p.dexId}:{}),address:p.pairAddress,baseToken:{address:p.baseToken.address,...(p.baseToken.name?{name:p.baseToken.name}:{}),...(p.baseToken.symbol?{symbol:p.baseToken.symbol}:{})},quoteToken:{address:p.quoteToken.address,...(p.quoteToken.name?{name:p.quoteToken.name}:{}),...(p.quoteToken.symbol?{symbol:p.quoteToken.symbol}:{})},...(num(p.priceUsd)!=null?{priceUsd:num(p.priceUsd)}:{}),...(num(p.liquidity?.usd)!=null?{liquidityUsd:num(p.liquidity?.usd)}:{}),...(num(p.volume?.h24)!=null?{volume24hUsd:num(p.volume?.h24)}:{}),...(p.pairCreatedAt!=null?{createdAt:p.pairCreatedAt}:{}),raw:p}} async search(q:string){return ((await this.get(`/latest/dex/search?q=${encodeURIComponent(q)}`,dsResponse)).pairs??[]).map(x=>this.map(x))} async getPair(chain:string,address:string){return ((await this.get(`/latest/dex/pairs/${encodeURIComponent(chain)}/${encodeURIComponent(address)}`,dsResponse)).pairs??[]).map(x=>this.map(x))} async getTokenPairs(chain:string,address:string){const x=await this.get(`/token-pairs/v1/${encodeURIComponent(chain)}/${encodeURIComponent(address)}`,z.array(dsPair));return x.map(p=>this.map(p))}}

const gtPool=z.object({id:z.string(),type:z.literal("pool"),attributes:z.object({address:z.string(),name:z.string().optional(),base_token_price_usd:numeric,reserve_in_usd:numeric,volume_usd:z.object({h24:numeric}).optional(),pool_created_at:z.string().optional()}).passthrough(),relationships:z.object({base_token:z.object({data:z.object({id:z.string()})}),quote_token:z.object({data:z.object({id:z.string()})}),dex:z.object({data:z.object({id:z.string()})}).optional()})});
const gtToken=z.object({id:z.string(),type:z.literal("token"),attributes:z.object({address:z.string(),name:z.string().optional(),symbol:z.string().optional(),decimals:z.number().optional(),total_supply:numeric,price_usd:numeric}).passthrough()});
export class GeckoTerminalClient extends HttpClient {constructor(o:Options={}){super("geckoterminal","https://api.geckoterminal.com/api/v2",o)} private map(p:z.infer<typeof gtPool>,network:string):MarketPair {const id=(x:string)=>x.includes("_")?x.slice(x.indexOf("_")+1):x;return {source:"geckoterminal",chainId:network,...(p.relationships.dex?{dexId:p.relationships.dex.data.id}:{}),address:p.attributes.address,baseToken:{address:id(p.relationships.base_token.data.id)},quoteToken:{address:id(p.relationships.quote_token.data.id)},...(num(p.attributes.base_token_price_usd)!=null?{priceUsd:num(p.attributes.base_token_price_usd)}:{}),...(num(p.attributes.reserve_in_usd)!=null?{liquidityUsd:num(p.attributes.reserve_in_usd)}:{}),...(num(p.attributes.volume_usd?.h24)!=null?{volume24hUsd:num(p.attributes.volume_usd?.h24)}:{}),raw:p}} private async pools(path:string,n:string){return (await this.get(path,z.object({data:z.array(gtPool)}))).data.map(x=>this.map(x,n))} trendingPools(n:string){return this.pools(`/networks/${n}/trending_pools`,n)} newPools(n:string){return this.pools(`/networks/${n}/new_pools`,n)} async getPool(n:string,a:string){return this.pools(`/networks/${n}/pools/${a}`,n).catch(async()=>[this.map((await this.get(`/networks/${n}/pools/${a}`,z.object({data:gtPool}))).data,n)])} async getToken(n:string,a:string){const x=(await this.get(`/networks/${n}/tokens/${a}`,z.object({data:gtToken}))).data;return {...x.attributes,address:x.attributes.address,priceUsd:num(x.attributes.price_usd),totalSupply:num(x.attributes.total_supply),raw:x}} async getOhlcv(n:string,p:string,period:"minute"|"hour"|"day",opts:{aggregate?:number;limit?:number}={}){const q=new URLSearchParams();if(opts.aggregate)q.set("aggregate",String(opts.aggregate));if(opts.limit)q.set("limit",String(opts.limit));const rows=(await this.get(`/networks/${n}/pools/${p}/ohlcv/${period}?${q}`,z.object({data:z.object({attributes:z.object({ohlcv_list:z.array(z.tuple([z.number(),z.number(),z.number(),z.number(),z.number(),z.number()]))})})}))).data.attributes.ohlcv_list;return rows.map(([timestamp,open,high,low,close,volume])=>({timestamp,open,high,low,close,volume}))}}

const bsToken=z.object({address:z.string(),name:z.string().nullable().optional(),symbol:z.string().nullable().optional(),decimals:numeric,total_supply:numeric,exchange_rate:numeric,holders_count:numeric}).passthrough();
export class BlockscoutClient extends HttpClient {constructor(o:Options&{baseUrl:string}){super("blockscout",o.baseUrl.replace(/\/$/,""),o)} async searchTokens(q:string){const x=await this.get(`/search?q=${encodeURIComponent(q)}`,z.object({items:z.array(z.object({type:z.string(),address:z.string(),name:z.string().nullable().optional(),symbol:z.string().nullable().optional()}).passthrough())}));return x.items.filter(i=>i.type==="token").map(i=>({...i,source:"blockscout" as const}))} async getToken(a:string){const x=await this.get(`/tokens/${a}`,bsToken);return {...x,decimals:num(x.decimals),totalSupply:num(x.total_supply),priceUsd:num(x.exchange_rate),holdersCount:num(x.holders_count),source:"blockscout" as const}} async getTokenHolders(a:string){const x=await this.get(`/tokens/${a}/holders`,z.object({items:z.array(z.object({address:z.object({hash:z.string()}),value:numeric}).passthrough())}));return x.items.map(i=>({address:i.address.hash,balance:num(i.value),raw:i}))} async getTokenTransfers(a:string){const x=await this.get(`/tokens/${a}/transfers`,z.object({items:z.array(z.object({from:z.object({hash:z.string()}).nullable(),to:z.object({hash:z.string()}).nullable(),total:z.object({value:numeric}),timestamp:z.string(),transaction_hash:z.string()}).passthrough())}));return x.items.map(i=>({from:i.from?.hash,to:i.to?.hash,value:num(i.total.value),timestamp:i.timestamp,transactionHash:i.transaction_hash,raw:i}))}}

type AggregateDeps={dexscreener:{search(q:string):Promise<MarketPair[]>};geckoterminal:{searchPools(q:string,network:string):Promise<MarketPair[]>}};
export interface AggregatedMarket extends Omit<MarketPair,"source"|"raw"> {sources:Source[];confidence:number;provenance:Array<{source:Source;pair:MarketPair}>;errors:Array<{source:Source;message:string}>}
export class MarketAggregator {constructor(private deps:AggregateDeps){} async search(q:string,o:{network:string}){const settled=await Promise.allSettled([this.deps.dexscreener.search(q),this.deps.geckoterminal.searchPools(q,o.network)]);const errors:Array<{source:Source;message:string}>=[];const all:MarketPair[]=[];settled.forEach((r,i)=>{const source:Source=i===0?"dexscreener":"geckoterminal";if(r.status==="fulfilled")all.push(...r.value);else errors.push({source,message:r.reason instanceof Error?r.reason.message:String(r.reason)})});const groups=new Map<string,MarketPair[]>();for(const p of all){const key=`${p.chainId}:${p.baseToken.address}:${p.quoteToken.address}`.toLowerCase();groups.set(key,[...(groups.get(key)??[]),p])}return [...groups.values()].map(ps=>{const prices=ps.flatMap(p=>p.priceUsd==null?[]:[p.priceUsd]);const spread=prices.length>1?(Math.max(...prices)-Math.min(...prices))/(prices.reduce((a,b)=>a+b,0)/prices.length):1;const confidence=Math.max(0,Math.min(1,(ps.length>1?.85:.55)-Math.min(.4,spread)));const first=ps[0]!;return {...first,sources:[...new Set(ps.map(p=>p.source))],priceUsd:prices.length?prices.reduce((a,b)=>a+b,0)/prices.length:first.priceUsd,liquidityUsd:Math.max(...ps.map(p=>p.liquidityUsd??0)),volume24hUsd:Math.max(...ps.map(p=>p.volume24hUsd??0)),confidence,provenance:ps.map(pair=>({source:pair.source,pair})),errors} as AggregatedMarket})}}
